export const appointmentList = [
  {
    id: 1,
    bookingid: "ID0000038",
    patientname: "Rajesh",
    type: "Fast Tag",
    time: "10:30 am",
    status: "Pending",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 2,
    bookingid: "ID0000039",
    patientname: "Samuel",
    type: "Non Fasttag",
    time: "1:30 pm",
    status: "Completed",
    department: "Consulting",
    assingned: "Dr.Sunny",
    link: "",
  },
  {
    id: 3,
    bookingid: "ID0000040",
    patientname: "Ramesh",
    type: "Fast Tag",
    time: "2:30 pm",
    status: "Cancelled",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 4,
    bookingid: "ID0000041",
    patientname: "Ramesh",
    type: "Non Fasttag",
    time: "2:30 pm",
    status: "Cancelled",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 5,
    bookingid: "ID0000042",
    patientname: "Ramesh",
    type: "Non Fasttag",
    time: "2:30 pm",
    status: "Completed",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 6,
    bookingid: "ID0000043",
    patientname: "Ramesh",
    type: "Fast Tag",
    time: "2:30 pm",
    status: "Cancelled",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 7,
    bookingid: "ID0000044",
    patientname: "Ramesh",
    type: "Fast Tag",
    time: "2:30 pm",
    status: "Pending",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
  {
    id: 8,
    bookingid: "ID0000044",
    patientname: "Ramesh",
    type: "Fast Tag",
    time: "2:30 pm",
    status: "Completed",
    department: "Consulting",
    assingned: "Dr.Jacob",
    link: "",
  },
];
